// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahxnmijhayjnvczttuyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeG5taWpoYXlqbnZjenR0dXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTcwMjQsImV4cCI6MjA2MDc5MzAyNH0.KEKB1i-xCv6Bk5B9FpnzSisqpVDAhaVqFfPqZn7osUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);